version: '3.8'

services:
  auth-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=auth_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8081:8080"]

  user-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=user_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8082:8080"]

  worker-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=worker_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8083:8080"]

  booking-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=booking_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8084:8080"]

  matching-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=matching_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8085:8080"]

  payment-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=payment_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8086:8080"]

  notification-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=notification_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8087:8080"]

  review-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=review_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8088:8080"]

  admin-service:
    build:
      context: ./jugaad_backend
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=admin_service
    env_file:
      - ./jugaad_backend/.env
    ports: ["8089:8080"]
